version: '3.9'
services:
  api:
    build:
      context: src/Lists
      dockerfile: Dockerfile
    ports:
      - 5100:5237
  seq:
    image: datalust/seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
  # -v /tmp/seq:/data
    ports:
      - 5020:80
      - 5341:5341
  
